FROM node:18-alpine

#create a app directory 
WORKDIR /app 

#install app dependencies 
COPY package*.json ./

#RUN npm install 
RUN npm install 

#bundle app souce 
copy . .

EXPOSE port 8080

CMD { "npm", "start" }