FROM node:14-alpine

#create a app directory 
WORKDIR /app

#install app dependencies 
COPY package*.json ./

#RUN npm install 
RUN npm install --verbose

#bundle app souce 
copy package*.json ./

EXPOSE  8080

CMD [ "npm", "start" ]